# Generated by Django 5.2 on 2025-05-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_vendor_businessaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='business_email',
            field=models.EmailField(max_length=254),
        ),
    ]
