# Generated by Django 5.2 on 2025-05-05 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_vendor_business_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
