# Generated by Django 5.2 on 2025-05-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_event_location_event_location_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_street_address',
            new_name='location_street_name',
        ),
    ]
