# Generated by Django 5.2 on 2025-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_event_vendor_id_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
